/**
 * Init command: generate master key, config file, and data directory.
 */

import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Command } from 'commander';
import { FileFallbackStorage } from '../../key-storage/file-fallback.js';
import { getKeyStorage } from '../../key-storage/index.js';
import { VaultManager } from '../../vault/index.js';
import { generateSelfSignedCert } from '../helpers.js';

export function register(program: Command): void {
  program
    .command('init')
    .description('Initialize Aegis — generate master key, config file, and data directory')
    .option(
      '--write-secrets',
      'Write master key to config file (convenient but less secure)',
      false,
    )
    .option(
      '--env-file',
      'Store master key in .env file instead of OS keychain (for CI/headless)',
      false,
    )
    .option('--generate-cert', 'Generate a self-signed TLS certificate for local dev use', false)
    .action((opts: { writeSecrets: boolean; envFile: boolean; generateCert: boolean }) => {
      const configPath = path.join(process.cwd(), 'aegis.config.yaml');
      if (fs.existsSync(configPath)) {
        console.log('\n  aegis.config.yaml already exists. To reinitialize, remove it first:\n');
        console.log('    rm aegis.config.yaml && aegis init\n');
        process.exit(1);
      }

      const masterKey = crypto.randomBytes(32).toString('hex');

      const dataDir = path.join(process.cwd(), '.aegis');
      if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
      }

      // Create the "default" vault through VaultManager (skip if it already exists)
      const manager = new VaultManager(dataDir);
      let salt: string;
      const existingVaults = manager.list();
      const existing = existingVaults.find((v) => v.name === 'default');
      if (existing) {
        salt = existing.salt;
      } else {
        const created = manager.create('default', masterKey);
        salt = created.salt;
      }

      // ── Store master key ────────────────────────────────────────
      let keyStorageMethod: 'keychain' | 'env-file' | 'config-file' | 'shown' = 'shown';

      if (opts.writeSecrets) {
        // Stored in config file (legacy flag)
        keyStorageMethod = 'config-file';
      } else if (opts.envFile) {
        // Stored in .env file (CI/headless mode)
        const envPath = path.join(process.cwd(), '.env');
        let envContent = '';
        if (fs.existsSync(envPath)) {
          envContent = fs.readFileSync(envPath, 'utf-8');
          // Remove existing AEGIS_MASTER_KEY line if present
          envContent = envContent.replace(/^AEGIS_MASTER_KEY=.*\n?/m, '');
        }
        envContent += `AEGIS_MASTER_KEY=${masterKey}\n`;
        fs.writeFileSync(envPath, envContent, { mode: 0o600 });
        keyStorageMethod = 'env-file';
      } else {
        // Default: store in OS keychain
        const keyStorage = getKeyStorage(dataDir);
        if (keyStorage.backend !== 'file' && keyStorage.isAvailable()) {
          try {
            keyStorage.setKey(masterKey);
            keyStorageMethod = 'keychain';
          } catch {
            // Keychain failed — auto-fallback to file storage
            console.log('\n  ⚠  OS keychain storage failed. Falling back to file storage.');
            try {
              const fileFallback = new FileFallbackStorage(dataDir);
              fileFallback.setKey(masterKey);
              keyStorageMethod = 'keychain'; // auto-stored in file fallback
              console.log(`    Key stored in ${dataDir}/.master-key (mode 0600)`);
              console.log(
                '    For better security, re-run with --env-file or fix your OS keychain.\n',
              );
            } catch {
              // File fallback also failed — show the key
              console.log('    File fallback also failed. Displaying key for manual storage.\n');
            }
          }
        } else {
          // No OS keychain available — store in file fallback
          keyStorage.setKey(masterKey);
          keyStorageMethod = 'keychain'; // File fallback is still auto-stored
        }
      }

      const masterKeyLine = opts.writeSecrets
        ? `  master_key: "${masterKey}"   # ⚠ stored in file — use OS keychain or env var for production`
        : '  # master_key: stored in OS keychain (run "aegis key where" to check)';

      const configContent = `# Aegis Configuration — generated by aegis init
# CLI flags override these values. Environment variables (AEGIS_*) override both.

gate:
  port: 3100
  # tls:
  #   cert: ./certs/aegis.crt
  #   key: ./certs/aegis.key
  # require_agent_auth: false

vault:
${masterKeyLine}
  name: default
  data_dir: ./.aegis

observability:
  log_level: info
  log_format: pretty
  metrics: true
  # dashboard:
  #   enabled: true
  #   port: 3200

# policies:
#   dir: ./policies
#   mode: enforce

# mcp:
#   transport: stdio
#   port: 3200

# webhooks: []
`;

      if (opts.writeSecrets) {
        fs.writeFileSync(configPath, configContent, { mode: 0o600 });
      } else {
        fs.writeFileSync(configPath, configContent, { mode: 0o644 });
      }

      console.log('\n  ╔══════════════════════════════════╗');
      console.log('  ║       Aegis Initialized ✓        ║');
      console.log('  ╚══════════════════════════════════╝\n');

      console.log('  Config file: aegis.config.yaml');
      console.log('  Default vault created (salt stored in vault registry)');

      // ── Key storage output ──────────────────────────────────────
      const keyStorage = getKeyStorage(dataDir);

      switch (keyStorageMethod) {
        case 'keychain':
          console.log(`\n  ✓ Master key stored in ${keyStorage.name}`);
          console.log('    The key is encrypted by your OS and never touches disk as plaintext.');
          console.log('    Run "aegis key where" to verify.\n');
          break;
        case 'env-file':
          console.log('\n  Master key saved to .env (mode 0600)');
          console.log('    ⚠  This file contains your master key in plaintext.');
          console.log('    Add .env to .gitignore if not already present.\n');
          break;
        case 'config-file':
          console.log('  Master key saved to aegis.config.yaml (mode 0600)\n');
          break;
        case 'shown':
          console.log('\n  ⚠  Store the following secret securely — it will NOT be shown again.\n');
          console.log(`  AEGIS_MASTER_KEY=${masterKey}\n`);
          console.log('  Export it in your shell profile or use a secrets manager:');
          console.log(`    export AEGIS_MASTER_KEY=${masterKey}\n`);
          console.log(
            '  Or re-run with --write-secrets to save it to the config file (less secure):',
          );
          console.log('    rm aegis.config.yaml && aegis init --write-secrets');
          break;
      }

      console.log(`  Vault salt: ${salt} (stored in .aegis/vaults.json)`);
      console.log('  Data directory: ./.aegis\n');
      console.log('  Next steps:');
      console.log(
        '    1. Add a credential:  aegis vault add --name slack --service slack --secret xoxb-... --domains api.slack.com',
      );
      console.log('    2. Start the gate:    aegis gate');
      console.log('    3. Point your agent:  http://localhost:3100/{service}/api/path\n');

      // Generate self-signed TLS certificate for local dev
      if (opts.generateCert) {
        generateSelfSignedCert(process.cwd());
      }
    });
}
