/**
 * Init command: generate master key, config file, and data directory.
 */

import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Command } from 'commander';
import { VaultManager } from '../../vault/index.js';
import { generateSelfSignedCert } from '../helpers.js';

export function register(program: Command): void {
  program
    .command('init')
    .description('Initialize Aegis — generate master key, config file, and data directory')
    .option(
      '--write-secrets',
      'Write master key to config file (convenient but less secure)',
      false,
    )
    .option('--generate-cert', 'Generate a self-signed TLS certificate for local dev use', false)
    .action((opts: { writeSecrets: boolean; generateCert: boolean }) => {
      const configPath = path.join(process.cwd(), 'aegis.config.yaml');
      if (fs.existsSync(configPath)) {
        console.log('\n  aegis.config.yaml already exists. To reinitialize, remove it first:\n');
        console.log('    rm aegis.config.yaml && aegis init\n');
        process.exit(1);
      }

      const masterKey = crypto.randomBytes(32).toString('hex');

      const dataDir = path.join(process.cwd(), '.aegis');
      if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
      }

      // Create the "default" vault through VaultManager (skip if it already exists)
      const manager = new VaultManager(dataDir);
      let salt: string;
      const existingVaults = manager.list();
      const existing = existingVaults.find((v) => v.name === 'default');
      if (existing) {
        salt = existing.salt;
      } else {
        const created = manager.create('default');
        salt = created.salt;
      }

      const masterKeyLine = opts.writeSecrets
        ? `  master_key: "${masterKey}"   # ⚠ stored in file — use env var for production`
        : `  # master_key: set AEGIS_MASTER_KEY env var (see below)`;

      const configContent = `# Aegis Configuration — generated by aegis init
# CLI flags override these values. Environment variables (AEGIS_*) override both.

gate:
  port: 3100
  # tls:
  #   cert: ./certs/aegis.crt
  #   key: ./certs/aegis.key
  # require_agent_auth: false

vault:
${masterKeyLine}
  name: default
  data_dir: ./.aegis

observability:
  log_level: info
  log_format: pretty
  metrics: true
  # dashboard:
  #   enabled: true
  #   port: 3200

# policies:
#   dir: ./policies
#   mode: enforce

# mcp:
#   transport: stdio
#   port: 3200

# webhooks: []
`;

      if (opts.writeSecrets) {
        fs.writeFileSync(configPath, configContent, { mode: 0o600 });
      } else {
        fs.writeFileSync(configPath, configContent, { mode: 0o644 });
      }

      console.log(`\n  ╔══════════════════════════════════╗`);
      console.log(`  ║       Aegis Initialized ✓        ║`);
      console.log(`  ╚══════════════════════════════════╝\n`);

      console.log(`  Config file: aegis.config.yaml`);
      console.log(`  Default vault created (salt stored in vault registry)`);

      if (opts.writeSecrets) {
        console.log(`  Master key saved to aegis.config.yaml (mode 0600)\n`);
      } else {
        console.log(`\n  ⚠  Store the following secret securely — it will NOT be shown again.\n`);
        console.log(`  AEGIS_MASTER_KEY=${masterKey}\n`);
        console.log(`  Export it in your shell profile or use a secrets manager:`);
        console.log(`    export AEGIS_MASTER_KEY=${masterKey}\n`);
        console.log(
          `  Or re-run with --write-secrets to save it to the config file (less secure):`,
        );
        console.log(`    rm aegis.config.yaml && aegis init --write-secrets`);
      }

      console.log(`\n  Vault salt: ${salt} (stored in .aegis/vaults.json)`);
      console.log(`  Data directory: ./.aegis\n`);
      console.log(`  Next steps:`);
      console.log(
        `    1. Add a credential:  aegis vault add --name slack --service slack --secret xoxb-... --domains api.slack.com`,
      );
      console.log(`    2. Start the gate:    aegis gate`);
      console.log(`    3. Point your agent:  http://localhost:3100/{service}/api/path\n`);

      // Generate self-signed TLS certificate for local dev
      if (opts.generateCert) {
        generateSelfSignedCert(process.cwd());
      }
    });
}
